package Exceptionalhandling;

public class ExceptionHandlingDemo {
	
	    public static void main(String[] args) {
	        try {
	        } catch (ArithmeticException e) {
	            System.out.println("An ArithmeticException occurred: " + e.getMessage());
	        } catch (Exception e) {
	            System.out.println("A general exception occurred: " + e.getMessage());
	        } finally {
	            System.out.println("Finally block executed.");
	        }

	        System.out.println("Program continues after exception handling.");
	    }
	}
